name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.272.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fa7b1803d38ec9a28f2949297f0c8ba06d9d2c346a1fb60399c3f84c81a6865"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
