name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.272.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "648b18470253c9da427640aa195fee323955cc3b9dec1dc572dd3e085a16b09b"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
