name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.274.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "226519a14079af26aa0d2ff41c2ff516e4773758554c22e4ea1a548e1612c041"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
